import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AkaneManager from '../components/pages/todo/characters/Akane/akaneManager'
import Header from '../components/header'

const Todo: NextPage = () => {
  return (
    // <div className={styles.container}>
    <div className="w-screen h-full dark:bg-black">
      <Head>
        <title>Todo Akane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <AkaneManager />
      </main>
    </div>
    // </div>
  )
}

export default Todo
