import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Akane from '../components/akane'

const Todo: NextPage = () => {
  return (
    <div className="dark">
      <div className="dark:bg-black">
        <div className={styles.container}>
          <Head>
            <title>Todo Akane</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <Akane />
          </main>
        </div>
      </div>
    </div >
  )
}

export default Todo
